project_id = "ygsbajattewcxdnazqph"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ygsbajattewcxdnazqph.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions]
enabled = true
port = 54323
max_size = 10485760

[functions.ai-generate]
verify_jwt = false

[storage]
enabled = true
port = 54324
file_size_limit = 52428800

[edge-runtime]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "bigquery"