// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygsbajattewcxdnazqph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc2JhamF0dGV3Y3hkbmF6cXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTUyOTksImV4cCI6MjA3MjEzMTI5OX0.AWO02tN3xufkDKy2_nW_aTqwSmN9dIQtSY-ZZbqQhkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});